@startuml
'https://plantuml.com/class-diagram

class Habit {
  - {static} gracePeriod: int = 4
  - name: String
  - deadline: DateTimeArg
  - interval: Duration
  - streak: int
  - clock: Clock

  + Habit(name: String, interval: Duration, clock: Clock)
  + Habit(name: String, deadline: DateTimeArg, interval: Duration, streak: int, clock: Clock)
  + incStreak(): StreakResult
  + getStreak(): int
  + toString(): String
  + toSaveString(): String
}

@enduml